site_name: HAN-IoT-LAB2324 | LoRaWAN Payload Encoder 

theme:
  name: material
  logo: images/logo.png
  favicon: images/LoRaWAN_Logo_DALLE.ico
  palette:
    primary: 'blue grey'
    accent: 'orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
  - mkdoxy:
      projects:
        Doxygen:
          src-dirs: include/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.hpp"
            RECURSIVE: True

nav:
  - Home: index.md
  - CayenneLPP Library: CayenneLPP_page.md
  - 'Doxygen Documentation':
    - 'Namespaces': 'Doxygen/namespaces.md'
    - 'Classes': 'Doxygen/classes.md'
    - 'Hierarchy': 'Doxygen/hierarchy.md'
    - 'Files': 'Doxygen/files.md'

copyright:
  Copyright (c) 2024 March by Klaasjan Wagenaar, Tristan Bosveld and Richard Kroesen