site_name: HAN-IoT-LAB2324 | LoRaWAN Payload Encoder 

theme:
  name: material
  palette:
    primary: 'blue grey'
    accent: 'orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
  - mkdoxy:
      projects:
        Doxygen:
          src-dirs: 
            include/
            test/
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.hpp"
            RECURSIVE: True

nav:
  - Home: index.md
  - CayenneLPP Library: CayenneLPP_page.md
  - 'Doxygen Documentation':
    - 'Namespaces': 'Doxygen/namespaces.md'
    - 'Classes': 'Doxygen/classes.md'
    - 'Hierarchy': 'Doxygen/hierarchy.md'
    - 'Files': 'Doxygen/files.md'
    - header: Doxygen\_cayenne_l_p_p_8hpp.md
    - src: Doxygen\_cayenne_l_p_p_8hpp_source.md
    - header types: Doxygen\_cayenne_references_8hpp.md
    - src types: Doxygen\_cayenne_references_8hpp_source.md
  - Unit Testing: Unit_tests_overview.md
  - Decoder: TTN_decoder.md
copyright:
  Copyright (c) 2024 March by Klaasjan Wagenaar, Tristan Bosveld and Richard Kroesen